name: Test Docker image

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          docker run -i $(docker build -q 14) /bin/sh -c "node --version && npm --version && git --version && python3 -V && make -v && g++ -v"
          docker run -i $(docker build -q 16) /bin/sh -c "node --version && npm --version && git --version && python3 -V && make -v && g++ -v"
          docker run -i $(docker build -q 14-3.13) /bin/sh -c "node --version && npm --version && git --version && python3 -V && make -v && g++ -v"
          docker run -i $(docker build -q 16-3.13) /bin/sh -c "node --version && npm --version && git --version && python3 -V && make -v && g++ -v"
